# Generated by Django 5.0.2 on 2024-03-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsmodel_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='news_description',
            field=models.TextField(max_length=100),
        ),
    ]
